### ISSUE TITLE
c'est crade

### ISSUE THREAD

**Issue by EmileCadorel** [GuillaumeGas/Chip8#1]
J'ai ouvert un fichier au hasard et c'est pas propre, tu peux faire quelque chose pour y remédier ?

**Comment by GuillaumeGas** [comment]
lol, où ça exactement. Je peux pas faire grand chose de différent pour les 36 instructions, j'ai viré les '_' immondes un peu partout par contre.

**Comment by EmileCadorel** [comment]
Pour le constructeur static en C++, il faut créer un structure interne et une instance de cette structure static.
```C++
// A.hh
class A {

    static class _init_ {
        public:
        _init_ () {
             // Les trucs que tu a envie de faire statiquement.
             Instruction [A::inst] = new A ();
        }
    } _initializer;
}
```

```C++
// A.cc
A::_init_ A::_initializer; // instanciation statique du constructeur
// ...
```
